# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  retrofit:
    target: ":diopa"
    import: "package:diopa_generator/diopa_generator.dart"
    builder_factories: ["diopaBuilder"]
    build_extensions: { ".dart": [".diopa.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
