# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  dioxide:
    target: ":dioxide"
    import: "package:dioxide_generator/dioxide_generator.dart"
    builder_factories: ["dioxideBuilder"]
    build_extensions: { ".dart": [".dioxide.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
