name: dioxide_generator
description: dioxide is a dio client generator.
version: 0.1.1+4
homepage: https://github.com/joutvhu/dioxide
repository: https://github.com/joutvhu/dioxide/tree/main/dioxide_generator

environment:
  sdk: '>=2.14.0 <3.0.0'

scripts:
  publish: dart pub publish

dependencies:
  dio: ^4.0.1
  source_gen: ^1.0.1
  built_collection: ^5.0.0
  code_builder: ^4.0.0
  tuple: ^2.0.0
  dioxide: ^0.1.1
  analyzer: ">=3.0.0 <6.0.0"
  dart_style: ^2.0.1
  build: ^2.0.1

dev_dependencies:
  lints: ">=1.0.0 <3.0.0"
  test: ^1.17.10
  source_gen_test: ^1.0.0
