name: dioxide
description: dioxide is a dio client generator.
version: 1.0.0
homepage: https://github.com/joutvhu/dioxide
repository: https://github.com/joutvhu/dioxide/tree/main/dioxide

environment:
  sdk: '>=2.17.0 <4.0.0'

scripts:
  publish: dart pub publish
  publish-dry: dart pub publish --dry-run

dependencies:
  dio: ^5.0.0
  meta: ^1.9.0

dev_dependencies:
  lints: ">=1.0.0 <3.0.0"
