name: dioxide
description: dioxide is a dio client generator.
version: 0.1.0
homepage: https://github.com/joutvhu/dioxide
repository: https://github.com/joutvhu/dioxide/tree/main/dioxide

environment:
  sdk: '>=2.14.0 <3.0.0'

scripts:
  publish: dart pub publish

dependencies:
  dio: ^4.0.1
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.0
