name: diopa
description: A starting point for Dart libraries or applications.
version: 1.0.0

homepage: https://github.com/joutvhu/diopa
repository: https://github.com/joutvhu/diopa

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dio: ^4.0.1
  meta: ^1.3.0

dev_dependencies:
  lints: ^1.0.0
